//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRVSS_PCS_WebMVC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InspectionBO", Namespace="http://schemas.datacontract.org/2004/07/VRVSS_PCS_BusinessService")]
    [System.SerializableAttribute()]
    public partial class InspectionBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string fnameField;
        
        private string lnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fnameField, value) != true)) {
                    this.fnameField = value;
                    this.RaisePropertyChanged("fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lnameField, value) != true)) {
                    this.lnameField = value;
                    this.RaisePropertyChanged("lname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInspectionData", ReplyAction="http://tempuri.org/IService1/GetInspectionDataResponse")]
        System.Collections.Generic.List<VRVSS_PCS_WebMVC.ServiceReference1.InspectionBO> GetInspectionData(VRVSS_PCS_WebMVC.ServiceReference1.InspectionBO inspectionBO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInspectionData", ReplyAction="http://tempuri.org/IService1/GetInspectionDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<VRVSS_PCS_WebMVC.ServiceReference1.InspectionBO>> GetInspectionDataAsync(VRVSS_PCS_WebMVC.ServiceReference1.InspectionBO inspectionBO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : VRVSS_PCS_WebMVC.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<VRVSS_PCS_WebMVC.ServiceReference1.IService1>, VRVSS_PCS_WebMVC.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<VRVSS_PCS_WebMVC.ServiceReference1.InspectionBO> GetInspectionData(VRVSS_PCS_WebMVC.ServiceReference1.InspectionBO inspectionBO) {
            return base.Channel.GetInspectionData(inspectionBO);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<VRVSS_PCS_WebMVC.ServiceReference1.InspectionBO>> GetInspectionDataAsync(VRVSS_PCS_WebMVC.ServiceReference1.InspectionBO inspectionBO) {
            return base.Channel.GetInspectionDataAsync(inspectionBO);
        }
    }
}
